### ISSUE TITLE
compute module is disabled

### ISSUE THREAD

**Issue by levackt** [lauraweindorf/enigma-dev-x#10]
Compute module is [currently disabled](https://github.com/enigmampc/EnigmaBlockchain/commit/1615567dabcf2dd67b223a05bc685e47fd827e36) in EnigmaBlockchain, so we can't deploy contracts if we build from the latest source.

**Comment by ainsleys** [comment]
Thanks for the heads up I will flag this

**Comment by assafmo** [comment]
To use the `compute` module please `git checkout v0.1.0`.
For now `master` is mainnet.

**Comment by levackt** [comment]
Thanks @assafmo
